version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 377348602056.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t fargate .
      - docker tag fargate:latest 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate:latest
  post_build:
    commands:
      - docker push 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate:latest
      - printf '[{"name":<TASK_DEFINITION_NAME>,"imageUri":"%s"}]' 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate:latest imagedefinitions.json
artifacts:
  files: imagedefinitions.json
