version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build -t fargate .
      - docker tag fargate:latest 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate:latest
  post_build:
    commands:
      - docker push 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate:latest
