version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build -t fargate1 .
      - docker tag fargate1:latest 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate1:latest
  post_build:
    commands:
      - docker push 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate1:latest
      - printf '[{"name":fargate-td,"imageUri":"%s"}]' 377348602056.dkr.ecr.ap-south-1.amazonaws.com/fargate1:latest imagedefinitions.json
artifacts:
  files: imagedefinitions.json
